[package]
name = "day03"
version = "0.1.0"
authors = ["Mathieu Lemay <acidrain1@gmail.com>"]
edition = "2021"

[dependencies]
aoc-common = { path = "../aoc-common" }
itertools = "0.12.0"
regex = "1.10.2"

[dev-dependencies]
rstest = "0.18.2"
