[package]
name = "day10"
version = "0.1.0"
authors = ["Mathieu Lemay <acidrain1@gmail.com>"]
edition = "2021"

[dependencies]
aoc-common = { path = "../aoc-common" }
itertools = "0.12.0"
pathfinding = "4.4.0"
geo = "0.27.0"

[dev-dependencies]
rstest = "0.18.2"
